/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.gson.Gson;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.io.IOUtils;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        try {
            String url = "http://localhost:8080/HelloWorldGradle/getUsers";

            String json = IOUtils.toString(new URL(url), Charset.forName("UTF-8"));

            System.out.println(json);
            Gson gson = new Gson();

            User[] users = gson.fromJson(json, User[].class);

            for (User user : users) {
                System.out.println(user);
            }

        } catch (MalformedURLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }
}
