/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SwingProject;

import SwingProject.controller.Controller;
import javax.swing.SwingUtilities;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        
        SwingUtilities.invokeLater(Controller::new);
    }
}
